[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 1024
max_test_rejects = 524288

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
